import 'package:flutter/material.dart';
import 'package:fprovid_app/Api/api-controller.dart';
import 'package:fprovid_app/Helpers/Theme/app_colors.dart';
import 'package:fprovid_app/Packages/Screens/Details/Components/Details/details-app.dart';
import 'package:fprovid_app/Packages/Screens/Details/Components/Header/header-data.dart';
import 'package:fprovid_app/Packages/Screens/Details/Model/auto-generrated.dart';
import 'package:fprovid_app/Packages/Screens/Details/Model/template.dart';
import 'package:fprovid_app/Packages/Widgets/Loading/app-loading.dart';
import 'package:fprovid_app/Packages/Widgets/Loading/enum-loading.dart';
import 'package:fprovid_app/services/language-status.dart';

class PageDetails extends StatelessWidget {
  PageDetails({required String id, String type = 'news'})
      : _id = id,
        _type = type;

  final String _id;
  final String _type;

  final ApiController _api = ApiController();

  // * get Data
  Future<AutoGenerated> getData(String lang) async {
    return await _api.getAppById(id: _id, type: _type, language: lang);
  }

  @override
  Widget build(BuildContext context) {
    bool _isDarkMode = Theme.of(context).brightness == Brightness.dark;
    return Scaffold(
      backgroundColor:
          _isDarkMode ? AppColors.darkMode : AppColors.blueDetailsBG,
      body: SafeArea(
        child: FutureBuilder<AutoGenerated>(
            future: getData(StatusLanguage.getLocalLangCode(context: context)),
            builder: (context, snapshot) {
              if (snapshot.connectionState == ConnectionState.waiting ||
                  !snapshot.hasData) {
                return Scaffold(
                  body: Center(
                    child: AppLoading(chooseLoading: ChooseLoading.PAGE),
                  ),
                );
              }
              Template _templateData = snapshot.data?.auto ?? Template();
              return Column(
                children: [
                  // * header
                  Container(
                    width: MediaQuery.of(context).size.width,
                    child: Center(child: HeaderData(data: _templateData)),
                  ),
                  // * details app
                  DetailsApp(data: _templateData),
                ],
              );
            }),
      ),
    );
  }
}
