import 'package:fprovid_app/Packages/Screens/Details/Model/auto-generrated.dart';
import 'package:fprovid_app/Packages/Screens/Games/Model/controller-game.dart';
import 'package:fprovid_app/Packages/Screens/News/Model/controller-news.dart';
import 'package:fprovid_app/Packages/Screens/Premium/Model/controller-premium.dart';
import 'package:fprovid_app/Packages/Screens/Social/Model/controller-social.dart';

abstract class HandleApi {
  // ? get Data News of a list ..
  Future<ModelControllerNews> getNews({required String language});
  // ? Get Data Game a List ..
  Future<ModelControllerGame> getGames({required String language});
  // ? Get Data Social a list ..
  Future<ModelControllerSocial> getSocial({required String language});
  // ? Get Data Premium  a list ..
  Future<ModelControllerPremium> getPremium({required String language});
  // ? Get Data AppDetile  a list ..
  Future<AutoGenerated> getAppById(
      {required String id, required String type, required String language});
}
