import 'template.dart';

class AutoGenerated {
  Template? auto;

  AutoGenerated({this.auto});

  AutoGenerated.fromJson(Map<String, dynamic> json, String type)
      : assert(json.isNotEmpty) {
    auto = json['$type'] != null ? new Template.fromJson(json['$type']) : null;
  }
}
